name: Rippledb CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'push' ||
      !startsWith(github.event.pull_request.head.label, 'rippledb:')

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Deploy
        if: |
          github.ref == 'refs/heads/master'
        run: |
          npm run deploy
