name: Rippledb CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'push' ||
      !startsWith(github.event.pull_request.head.label, 'rippledb:')

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@master

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
          
      - name: Install Dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: |
          yarn
        env:
          CI: true

      - name: Deploy
        if: |
          github.ref == 'refs/heads/master'
        run: |
          git config --global user.email "heineiuo@gmail.com"
          git config --global user.name "heineiuo"
          git config --global user.password ${{ secrets.RIPPLEDB_BOT_GITHUB_TOKEN }}
          GIT_USER=heineiuo yarn deploy
